resolver: lts-7.19
compiler: ghc-8.0.2

docker:
  enable: true

packages:
- '.'
- location:
    git: git@github.com:CthulhuDen/ghc-mod.git
    commit: e98afbcf76a5b7754887648f0e39c9adfe0de601
  extra-dep: true

# Dependency packages to be pulled from upstream that are not in the resolver
extra-deps:
- 'servant-0.9.1.1'
- 'servant-client-0.9.1'
- 'http-api-data-0.3.5'

- 'hlint-1.9.41'
- 'haskell-src-exts-1.19.1'

# Override default flag values for local packages and extra-deps
flags: {}
